name: Build Android APK

on:
  push:
    branches: ['main']

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Cache sveltekit artifacts
        uses: actions/cache@v4
        with:
          path: |
            .svelte-kit
            node_modules/.vite
          key: ${{ runner.os }}-vite-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-vite-

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Svelte project
        run: pnpm build

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Capacitor sync
        run: pnpm cap sync android

      - name: Build APK
        run: cd android && ./gradlew assembleRelease

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > my-release-key.keystore
          ls -lh my-release-key.keystore

      - name: List files
        run: ls -lh

      - name: Show keystore details
        run: file my-release-key.keystore

      - name: Validate keystore
        run: |
          keytool -list -keystore my-release-key.keystore -storepass ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
          -keystore my-release-key.keystore \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          android/app/build/outputs/apk/release/app-release-unsigned.apk ${{ secrets.KEY_ALIAS }}

      - name: Align APK
        run: |
          zipalign -v 4 \
          android/app/build/outputs/apk/release/app-release-unsigned.apk \
          android/app/build/outputs/apk/release/app-release-signed.apk

      - name: Verify APK signing
        run: jarsigner -verify android/app/build/outputs/apk/release/app-release-signed.apk

      - name: Check APK exists
        run: |
          ls -lh android/app/build/outputs/apk/release/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release-signed.apk
